# Generated by Django 5.2.11 on 2026-02-06 23:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionAbc',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_abc', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1)),
                ('fecha_clasificacion', models.DateField(auto_now_add=True)),
                ('ventas_acumuladas', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Clasificación ABC',
                'verbose_name_plural': 'Clasificaciones ABC',
                'db_table': 'clasificacion_abc',
                'ordering': ['categoria_abc', '-ventas_acumuladas'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detallecompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detallecompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalleventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalleventa',
            },
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_VENTA', 'Salida por Venta'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('DEVOLUCION', 'Devolución'), ('MERMA', 'Merma')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_inventario', to='api.compra')),
            ],
            options={
                'verbose_name': 'Historial de Inventario',
                'verbose_name_plural': 'Historiales de Inventario',
                'db_table': 'historial_inventario',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('punto_reorden', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('demanda_promedio_diaria', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tiempo_entrega_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_seguridad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_venta', models.DateField(blank=True, null=True)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_inventario', models.CharField(choices=[('NORMAL', 'Normal'), ('BAJO', 'Bajo'), ('CRITICO', 'Crítico'), ('SOBRESTOCK', 'Sobrestock')], default='NORMAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='OrdenReabastecimiento',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_sugerida', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PROCESADA', 'Procesada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('motivo', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_CRITICO', 'Stock Crítico'), ('REORDEN', 'Punto de Reorden'), ('DEMANDA_ALTA', 'Demanda Alta'), ('MANUAL', 'Manual')], max_length=50)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reabastecimiento', to='api.compra')),
            ],
            options={
                'verbose_name': 'Orden de Reabastecimiento',
                'verbose_name_plural': 'Órdenes de Reabastecimiento',
                'db_table': 'orden_reabastecimiento',
                'ordering': ['-fecha_sugerencia', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('L', 'Litro'), ('UND', 'Unidad'), ('M', 'Metro'), ('CAJA', 'Caja')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('MATERIA_PRIMA', 'Materia Prima'), ('PRODUCTO_TERMINADO', 'Producto Terminado'), ('INSUMO', 'Insumo'), ('HERRAMIENTA', 'Herramienta')], max_length=20)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id_prodprov', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_entrega_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('es_proveedor_principal', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedores', to='api.producto')),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'db_table': 'producto_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='SegmentoKmeans',
            fields=[
                ('id_segmento', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_label', models.IntegerField()),
                ('fecha_segmento', models.DateField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_kmeans', to='api.producto')),
            ],
            options={
                'verbose_name': 'Segmento K-means',
                'verbose_name_plural': 'Segmentos K-means',
                'db_table': 'segmento_kmeans',
                'ordering': ['-fecha_segmento'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='api.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='ordenreabastecimiento',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_reabastecimiento', to='api.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_producto',
            field=models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.producto'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='historial_inventario', to='api.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='api.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='api.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='api.producto'),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_abc', to='api.producto'),
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedores', to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='api.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_persona',
            field=models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.persona'),
        ),
        migrations.AddField(
            model_name='ordenreabastecimiento',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_reabastecimiento', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='historial_inventario', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_inventario', to='api.venta'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together={('id_producto', 'id_proveedor')},
        ),
    ]
