# Generated by Django 5.2.11 on 2026-02-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clasificacionabc_compra_detallecompra_detalleventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('INSTRUMENTO', 'Instrumento'), ('ACCESORIO', 'Accesorio'), ('REPUESTO', 'Repuesto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UND', 'Unidad'), ('CAJA', 'Caja'), ('PIEZA', 'Pieza')], max_length=20),
        ),
    ]
