# Generated by Django 5.2.11 on 2026-02-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR')], default='EFECTIVO', max_length=20),
        ),
    ]
