# Generated by Django 5.2.11 on 2026-03-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venta_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='api.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
