# Generated by Django 5.2.11 on 2026-03-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_proveedor_activo_proveedor_nit_proveedor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='api.producto'),
        ),
    ]
