# Generated by Django 5.2.11 on 2026-03-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_detallecompra_id_producto'),
    ]

    operations = [
        # 1. Crear tabla Categoria
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'categoria', 'ordering': ['nombre']},
        ),

        # 2. Crear tabla ConfiguracionTienda
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(default='Mi Tienda', max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ruc_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('simbolo_moneda', models.CharField(default='Bs.', max_length=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'configuracion_tienda'},
        ),

        # 3. Agregar columna id_categoria_nueva como nullable (sin tocar la columna vieja)
        migrations.AddField(
            model_name='producto',
            name='categoria_nueva',
            field=models.ForeignKey(
                blank=True, null=True,
                db_column='id_categoria',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos',
                to='api.categoria',
            ),
        ),

        # 4. Eliminar el campo viejo categoria (CharField)
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),

        # 5. Renombrar categoria_nueva → categoria
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_nueva',
            new_name='categoria',
        ),
    ]