# Generated by Django 5.2.11 on 2026-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categoria_configuraciontienda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='configuraciontienda',
            options={'verbose_name': 'Configuración de Tienda'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
