# Generated by Django 5.2.11 on 2026-04-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialinventario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_inventario', to='api.usuario'),
        ),
    ]
