# Generated by Django 5.2.11 on 2026-05-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_historialinventario_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionModelo',
            fields=[
                ('id_ejecucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('PARCIAL', 'Parcial')], default='EXITOSO', max_length=10)),
                ('anio_analizado', models.IntegerField()),
                ('mes_analizado', models.IntegerField()),
                ('productos_procesados', models.IntegerField(default=0)),
                ('productos_reclasificados', models.IntegerField(default=0)),
                ('silhouette_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('anomalias_detectadas', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejecucion_modelo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='clasificacionabc',
            options={'ordering': ['-anio', '-mes', 'categoria_abc']},
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='anio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='categoria_anterior',
            field=models.CharField(blank=True, choices=[('A', 'Categoría A — Alta prioridad'), ('B', 'Categoría B — Prioridad media'), ('C', 'Categoría C — Baja prioridad')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='cluster_kmeans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='confianza',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='distancia_centroide',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='hubo_cambio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='mes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='motivo_cambio',
            field=models.CharField(blank=True, choices=[('CALCULO_INICIAL', 'Cálculo inicial'), ('AUMENTO_VENTAS', 'Aumento de ventas'), ('DESCENSO_VENTAS', 'Descenso de ventas'), ('SIN_MOVIMIENTO', 'Sin movimiento'), ('REACTIVACION', 'Reactivación'), ('ESTACIONAL', 'Cambio estacional')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='pct_ingresos_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='pct_ingresos_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='clasificacionabc',
            name='categoria_abc',
            field=models.CharField(choices=[('A', 'Categoría A — Alta prioridad'), ('B', 'Categoría B — Prioridad media'), ('C', 'Categoría C — Baja prioridad')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clasificacionabc',
            name='fecha_clasificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clasificacionabc',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_abc', to='api.producto'),
        ),
        migrations.AlterField(
            model_name='clasificacionabc',
            name='ventas_acumuladas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalleventa_set', to='api.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionabc',
            unique_together={('id_producto', 'anio', 'mes')},
        ),
        migrations.CreateModel(
            name='MetricaProducto',
            fields=[
                ('id_metrica', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria_nombre', models.CharField(default='Sin categoría', max_length=50)),
                ('stock_al_calcular', models.IntegerField(default=0)),
                ('unidades_vendidas', models.IntegerField(default=0)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('num_transacciones', models.IntegerField(default=0)),
                ('dias_con_venta', models.IntegerField(default=0)),
                ('frecuencia_venta', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('rotacion_inventario', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variacion_unidades_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('variacion_ingresos_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tendencia', models.CharField(choices=[('SUBIENDO', 'Subiendo'), ('ESTABLE', 'Estable'), ('BAJANDO', 'Bajando')], default='ESTABLE', max_length=10)),
                ('score_abc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_abc', to='api.producto')),
            ],
            options={
                'db_table': 'metrica_producto',
                'ordering': ['-anio', '-mes', '-score_abc'],
                'unique_together': {('id_producto', 'anio', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='clasificacionabc',
            name='id_metrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificacion', to='api.metricaproducto'),
        ),
    ]
