# Generated by Django 5.2.11 on 2026-05-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ejecucionmodelo_alter_clasificacionabc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionabc',
            name='es_anomalia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricaproducto',
            name='detalle_anomalia',
            field=models.TextField(blank=True, help_text='Descripción de qué variable disparó la detección.', null=True),
        ),
        migrations.AddField(
            model_name='metricaproducto',
            name='es_anomalia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricaproducto',
            name='factor_penalizacion',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Factor multiplicador aplicado al score (0.5-1.0).', max_digits=4),
        ),
        migrations.AddField(
            model_name='metricaproducto',
            name='score_abc_ajustado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score ABC después de aplicar penalización por anomalía.', max_digits=6),
        ),
        migrations.AddField(
            model_name='metricaproducto',
            name='score_anomalia',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Score de Isolation Forest. Más negativo = más anómalo.', max_digits=8, null=True),
        ),
    ]
